---
title: "purchase_propensity_2"
author: "Gustavo Duarte"
date: "`r Sys.Date()`"
output: 
    html_document:
      highlight: textmate
      logo: logo.png
      theme: jou
      number_sections: no
      toc: yes
      toc_float:
        collapsed: yes
        smooth_scroll: no
      df_print: paged
      code_folding: hide
---

# 0 - Starting point

## 0.0 - Installing Packages

```{r results = 'hide'}
install.packages("tidyverse")
install.packages("janitor")
install.packages("skimr")
install.packages("gtsummary")
install.packages("summarytools")
install.packages("kableExtra")
install.packages("gridExtra")
```

## 0.1 - Importing libraries

```{r results = 'hide'}
library(tidyverse)
library(readr) # leitura de arquivos .csv
library(janitor) # nomes de colunas em caixa baixa e espaços em _
library(skimr) # gera um dataframe de estatísticas para variáveis numéricas
library(gtsummary) # gera uma figura sumarizando as variáveis
library(summarytools)
```

# 1 - Data loading, checking, cleaning and description

```{r}
# Loading data:

df <- readr::read_csv("train.csv")
#View(df)
#dplyr::glimpse(df)
```

```{r}
# Checking first rows
df %>% head
```

```{r}
# Colocando nome das colunas em caixa baixa
df <- janitor::clean_names(df)

df %>% head
```

```{r}
# Data types

dplyr::tibble(features = colnames(df), 
              data_tipe = unlist(lapply(df, typeof))
              )
```

```{r}
# Data dimensions

dplyr::tibble( dimension = unlist(list("rows", "columns")),
               count = c(dim(df)[1], dim(df)[2]))
```

```{r}
# Checking NA's

dplyr::tibble(variable = colnames(df),
              number_of_missing = colSums(is.na(df)))
```

```{r}
# 1 - Replacing some column names (rename() function)

# 2 - Changing categorical columns elements to lowercase

# 3 - Changing 'vehicle_age' column values

# 4 - Changin character columns to factor

# função mutate: nome da variável, operação a fazer na variável
# função across: aplica uma função à multiplas colunas

df <- df %>% 
  
  # renomear colunas -> rename(nome_novo, nome_antigo)
  dplyr::rename(days_associated = vintage,
                health_annual_paid = annual_premium) %>% 
  
  # mutate(nome_da_variável, operacao)
  dplyr::mutate(
    
                # colunas categóricas -> valores em lowercase
                across(where(is.character), tolower),
                
                # colunas com valores 1 ou 0 -> substituir por "yes" ou "no"
                
                driving_license = ifelse(driving_license==1, "yes", "no"),
                
                previously_insured = ifelse(previously_insured==1, "yes", "no"),
                
                response = ifelse(response==1, "yes", "no"),
                
                # coluna "vehicle_age" -> substituindo os valores
                vehicle_age = case_when(
                                        vehicle_age == "< 1 year" ~ "less_than_1_year",
                                        vehicle_age == "1-2 year" ~ "between_1_and_2_years",
                                        vehicle_age == "> 2 years" ~ "more_than_1_year"
                                        )
    
               ) %>% 
  
  # convertendo variáveis de caracter p/ factor
  dplyr::mutate_if(is.character, as.factor)
  

```

```{r}
# Adjusting "yes"/"no" variables to ordered factor:

## Ajustando as variáveis de yes/no colocando "yes" no primeiro nível do factor

df <- df %>% mutate(
                    # response variable
                    response = factor(response, levels=c("yes", "no")),
                    
                    # driving_license
                    driving_license = factor(driving_license, levels=c("yes", "no")),
                    
                    # previously_insured
                    previously_insured = factor(previously_insured, levels=c("yes", "no")),
                    
                    # vehicle_damage
                    vehicle_damage = factor(vehicle_damage, levels=c("yes","no"))
                    )
```

```{r include=FALSE}
# Contando a quantidade de "yes" e "no" na variável resposta após a conversão p/ factor ord

df$response %>% table
```

```{r}
# Saving df as rds file
base::saveRDS(df, "df_cleaned.rds")
```

```{r}
# Loading RDS file
df <- base::readRDS("df_cleaned.rds")

df %>% head
```

```{r}
# Descripitive statistics

skimr::skim(df) 
```

```{r}
# Pacote gtsummary -> cria sumários de tabelas

df %>% 
  select(-id) %>% 
  gtsummary::tbl_summary(
                          type = list(response ~ "categorical",
                                      driving_license ~ "categorical",
                                      previously_insured ~ "categorical",
                                      vehicle_damage ~ "categorical"),
                          
                          digits = list(all_categorical() ~ c(0,2))
  )
```

Statistics of numerical attributes

```{r}
# Numerical attributes -> descriptive statistical evaluation

num_attributes <- df %>% 
                        select(age, days_associated, health_annual_paid) 
  
  
# comando abaixo gera um descritivo estatístico
num_attributes_stats <- descr(num_attributes, style = "rmarkdown") %>% 
  
                        round(2)

# comando abaixo formata/organiza a saída do comando acima
kableExtra::kable(data.frame(num_attributes_stats), format = "html") %>% 
                  
          kableExtra::kable_styling(bootstrap_options = "striped",
                                    full_width = FALSE)
```

Categorical attributes

```{r include=FALSE}
categ_attributes <- df %>% 
                        select(-id, -colnames(num_attributes)) 

categ_attributes
```

# 2 - EDA

## 2.1 Univariate

### 2.1.1 Numerical attributes

```{r include=FALSE}
# Histogram

# Age ================================

age_plot <- num_attributes %>% 
  
  ggplot(aes(x=age)) + # informar o dado que irá no eixo da figura
  
  geom_histogram(aes(y=after_stat(density)),
                 binwidth = 1,
                 color="red", 
                 fill="green",
                 alpha=0.5) + # alpha -> controla a transparência
  
  geom_density(color="blue") +
  
  labs(x= "Age", y= "Density", title = "Histograma de frequências para idade") +
  
  theme_bw()

age_plot  
```

```{r include=FALSE}
# Days associated ================================

days_associated_plot <- num_attributes %>% 
  
  ggplot(aes(x=days_associated)) + # informar o dado que irá no eixo da figura
  
  geom_histogram(aes(y=after_stat(density)),
                 binwidth = 50,
                 color="red", 
                 fill="green",
                 alpha=0.5) + # alpha -> controla a transparência
  
  geom_density(color="blue") +
  
  labs(x= "Days associated", y= "Density", title = "Histograma de frequências para Days associated") +
  
  theme_bw()

days_associated_plot
```

```{r include=FALSE}
# Health annual paid ================================

health_annual_paid_plot <- num_attributes %>% 
  
  ggplot(aes(x=health_annual_paid)) + # informar o dado que irá no eixo da figura
  
  geom_histogram(aes(y=after_stat(density)),
                 binwidth = 10000,
                 color="red", 
                 fill="green",
                 alpha=0.5) + # alpha -> controla a transparência
  
  geom_density(color="blue") +
  
  labs(x= "Health annual paid", y= "Density", title = "Histograma de frequências para Health annual paid") +
  
  theme_bw()

health_annual_paid_plot
```

```{r}
# Unir os 3 histogramas anteriores

gridExtra::grid.arrange(age_plot, days_associated_plot, health_annual_paid_plot,
                        ncol=3)
```

```{r include=FALSE}
# Removing unused objects

rm(num_attributes)
rm(num_attributes_stats)
rm(age_plot)
rm(days_associated_plot)
rm(health_annual_paid_plot)
gc()
```

### 2.2.2 Categorical attributes

```{r}

# Gender ============================================================
gender_plot <- categ_attributes %>% 
               ggplot(aes(x=gender)) +
               geom_bar(aes(fill=gender), color="black", show.legend = FALSE) +
               labs(x="Gender", y="Count", title = "Barplot of Gender") +
               theme_bw()

# Driving license ===================================================
driving_license_plot <- categ_attributes %>% 
                        ggplot(aes(x=driving_license)) +
                        geom_bar(aes(fill=driving_license), color="black", show.legend = FALSE) +
                        labs(x="Driving License", y="Count", title = "Barplot of Driving License") +
                        theme_bw()

# Previously insured ===============================================
previously_insuredr_plot <- categ_attributes %>% 
  ggplot(aes(x=previously_insured)) +
  geom_bar(aes(fill=previously_insured), color="black", show.legend = FALSE) +
  labs(x="Previously insured", y="Count", title = "Barplot of Previously insured") +
  theme_bw()


# Vehicle age ======================================================
vehicle_age_plot <- categ_attributes %>% 
                    ggplot(aes(x=vehicle_age)) +
                    geom_bar(aes(fill=vehicle_age), color="black", show.legend = FALSE) +
                    labs(x="Vehicle age", y="Count", title = "Barplot of Vehicle age") +
                    theme_bw()


# Vehicle demage ==================================================
vehicle_damage_plot <- categ_attributes %>% 
                    ggplot(aes(x=vehicle_damage)) +
                    geom_bar(aes(fill=vehicle_damage), color="black", show.legend = FALSE) +
                    labs(x="Vehicle demage", y="Count", title = "Barplot of Vehicle demage") +
                    theme_bw()


# Response =======================================================
response_plot <- categ_attributes %>% 
                 ggplot(aes(x=response)) +
                 geom_bar(aes(fill=response), color="black", show.legend = FALSE) +
                 labs(x="Response", y="Count", title = "Barplot of Response") +
                 theme_bw()




# Figura multipainéis

gridExtra::grid.arrange(gender_plot, driving_license_plot, previously_insuredr_plot,
                        vehicle_age_plot, vehicle_damage_plot, response_plot,
                        ncol=3)
```

```{r include=FALSE}
# Getting rid of unused objects

rm(categ_attributes)
rm(driving_license_plot)
rm(gender_plot)
rm(previously_insuredr_plot)
rm(response_plot)
rm(vehicle_age_plot)
rm(vehicle_damage_plot)
gc()
```

## 2.2 Bivariate

### Numéricas X Numéricas

```{r}
# Numéricas -> age X health_annual_paid

df %>%
      select(age, region_code, days_associated, health_annual_paid, response) %>%
      
      ggplot(aes(x=age, y=health_annual_paid),) + 
      
      geom_point(aes(color=response))

```

### Numéricas X Categóricas

```{r}
df %>% 
      ggplot(aes(y=age, x=gender)) +
      stat_boxplot(geom='errorbar', width=0.6) +
      geom_boxplot(aes(fill=gender), show.legend = FALSE) +
      facet_wrap(vars(response)) +
      labs(x="gender", title="Response (Yes/No) -> Age X Gender")
  
```

```{r}
df %>% 
      ggplot(aes(y=age, x=vehicle_age)) +
      stat_boxplot(geom='errorbar', width=0.6) +
      geom_boxplot(aes(fill=vehicle_age), show.legend = FALSE) +
      facet_wrap(vars(response)) +
      labs(x="Vehicle Age", title="Response (Yes/No) -> Age X Vehicle Age") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1)) # rotacionar x ticks
```

```{r}
df %>% 
      ggplot(aes(y=health_annual_paid, x=gender)) +
      stat_boxplot(geom='errorbar', width=0.6) +
      geom_boxplot(aes(fill=gender), show.legend = FALSE) +
      facet_wrap(vars(response)) +
      labs(x="gender", title="Response (Yes/No) -> Health annual paid X Gender")
```

```{r}
df %>% 
      ggplot(aes(y=health_annual_paid, x=vehicle_age)) +
      stat_boxplot(geom='errorbar', width=0.6) +
      geom_boxplot(aes(fill=vehicle_age), show.legend = FALSE) +
      facet_wrap(vars(response)) +
      labs(x="health_annual_paid", title="Response (Yes/No) -> Health Annual Paid X Vehicle Age") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1)) # rotacionar x ticks

```

```{r}
df %>% 
  select(age, response) %>% 
  ggplot(aes(x=age)) +
  geom_histogram(binwidth = 5, aes(fill=response)) +
  facet_wrap(vars(response), nrow=2, scales="free_y") +
  labs(title="Age histogram")

```

```{r}

# Variável Age é diferente entre Response yes e no?

df %>% 
  select(age, response) %>% 
  gtsummary::tbl_summary(by=response, list(response ~ "categorical")) %>% 
  add_p()
```

### Categóricas X Categóricas

```{r}
# Categóricas X Categóricas

# Driving licence
df %>% 
  ggplot(aes(x=driving_license)) +
  geom_bar(aes(fill=driving_license)) +
  facet_wrap(vars(response), scales="free_y") +
  labs(title="driving_license x Response")
```

```{r}
df %>% 
  ggplot(aes(x=gender)) +
  geom_bar(aes(fill=gender)) +
  facet_wrap(vars(response), scales="free_y") +
  labs(title="Gender x Response")

```

```{r}
# Vehicle damage
df %>% 
  ggplot(aes(x=vehicle_damage)) +
  geom_bar(aes(fill=vehicle_damage)) +
  facet_wrap(vars(response), scales="free_y") +
  labs(title="Vehicle damage x Response")
```

```{r}
# Vehicle damage
df %>% 
  ggplot(aes(x=vehicle_age)) +
  geom_bar(aes(fill=vehicle_age)) +
  facet_wrap(vars(response), scales="free_y") +
  labs(title="vehicle_age x Response") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) # rotacionar x ticks
```

```{r}
df 
```

## 2.3 Multivariate

```{r}

```

```{r}

```
